export * from './icons-page/icons-page.component';
export * from './badge-page/badge-page.component';
export * from './cards-page/cards-page.component';
export * from './modal-page/modal-page.component';
export * from './carousel-page/carousel-page.component';
export * from './tooltips-page/tooltips-page.component';
export * from './tabs-page/tabs-page.component';
export * from './progress-page/progress-page.component';
export * from './widget-page/widget-page.component';
